data_params:
  data_seed: 2024
  train_path: /home/sheng136/BBScore/data/wikisection/wikisection.train.txt
  test_path: /home/sheng136/BBScore/data/wikisection/wikisection.test.txt
model_params:
  latent_dim: 8
  n_layers: 2 # number of mlps in the encoder
  eps: 1e-6
  hidden_size: 128
  model_name: gpt2
loss_params:
  loss: brownian_loss
  name: triplet
optim_params:
  batch_size: 32
  optimizer: AdamW
  decay_steps: 5e4
  decay_factor: 0.01
  learning_rate: 0.0001
  moving_average_decay: 0.9999
  momentum: 0.9
experiment_params:
  checkpoint_epochs: 10
  num_epochs: 1
  device: cuda:0
  seed: 2024
  data_loader_workers: 4
  exp_dir: exp
  exp_name: BBencoder_train
